[package]
name = "mmkv"
version = "0.1.0"
edition = "2021"
authors = ["Kexuan Yang <kexuan.yang@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "3.2.0" }
memmap2 = { version = "0.5.10" }

[build-dependencies]
protobuf-codegen = { version = "3.2.0"}
protoc-bin-vendored = { version = "3.0.0" }