name: Android Build Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Decode Keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
      run: echo ${ENCODED_KEYSTORE} | base64 -di > ./android/app/keystore.jks

    - name: Build with Gradle
      env:
        SIGN_KEY_STORE_PATH: keystore.jks
        SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
        SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
      run: |
        cd ./android
        echo SIGN_KEY_STORE_PATH=keystore.jks >> local.properties
        echo SIGN_STORE_PASSWORD=${SIGN_STORE_PASSWORD} >> local.properties
        echo SIGN_KEY_ALIAS=${SIGN_KEY_ALIAS} >> local.properties
        echo SIGN_KEY_PASSWORD=${SIGN_KEY_PASSWORD} >> local.properties
        chmod +x gradlew
        ./gradlew clean
        ./gradlew assembleDebug
