name: Publish Android package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG
        env:
          signingSecret: ${{ secrets.GPG_SECRET }}
        run: |
          echo ${signingSecret} | base64 -di | gpg --dearmor > ./android/secret.gpg
      - name: Android publish
        env:
          sonatypeUsername: ${{ secrets.SONATYPEUSERNAME }}
          sonatypePassword: ${{ secrets.SONATYPEPASSWORD }}
          signingKeyId: ${{ secrets.GPG_KEY_ID }}
          signingPwd: ${{ secrets.GPG_PWD }}
        run: |
          cd ./android
          echo sonatypeUsername=${sonatypeUsername} >> local.properties
          echo sonatypePassword=${sonatypePassword} >> local.properties
          echo signing.keyId=${signingKeyId} >> local.properties
          echo signing.password=${signingPwd} >> local.properties
          echo signing.secretKeyRingFile=secret.gpg >> local.properties
          chmod +x gradlew
          ./gradlew publish