name: Publish Android package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Decode Keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
        GPG_SECRET: ${{ secrets.GPG_SECRET }}
      run: |
        echo ${ENCODED_KEYSTORE} | base64 -di > ./android/app/keystore.jks
        echo ${GPG_SECRET} | base64 -di | gpg --dearmor > ./android/secret.gpg

    - name: Android publish
      env:
        SIGN_KEY_STORE_PATH: keystore.jks
        SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
        SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
        SONATYPEUSERNAME: ${{ secrets.SONATYPEUSERNAME }}
        SONATYPEPASSWORD: ${{ secrets.SONATYPEPASSWORD }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PWD: ${{ secrets.GPG_PWD }}
      run: |
        cd ./android
        echo SIGN_KEY_STORE_PATH=keystore.jks >> local.properties
        echo SIGN_STORE_PASSWORD=${SIGN_STORE_PASSWORD} >> local.properties
        echo SIGN_KEY_ALIAS=${SIGN_KEY_ALIAS} >> local.properties
        echo SIGN_KEY_PASSWORD=${SIGN_KEY_PASSWORD} >> local.properties
        echo sonatypeUsername=${SONATYPEUSERNAME} >> local.properties
        echo sonatypePassword=${SONATYPEPASSWORD} >> local.properties
        echo signing.keyId=${GPG_KEY_ID} >> local.properties
        echo signing.password=${GPG_PWD} >> local.properties
        echo signing.secretKeyRingFile=../secret.gpg >> local.properties
        chmod +x gradlew
        ./gradlew clean
        ./gradlew publish
