name: Cargo Test

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'build.rs'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'build.rs'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Clippy default
        run: cargo clippy --all-targets -- -D warnings
      - name: Clippy feature encryption
        run: cargo clippy --all-targets --features encryption -- -D warnings
      - name: Build default
        run: cargo build --verbose -r
      - name: Build feature encryption
        run: cargo build --features encryption --verbose -r
      - name: Run default tests
        run: cargo test --verbose -r
      - name: Run feature encryption tests
        run: cargo test --features encryption --verbose -r
