name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build default
      run: cargo build --verbose
    - name: Build feature encryption
      run: cargo build --features encryption --verbose
    - name: Run default tests
      run: cargo test --verbose
    - name: Run feature encryption tests
      run: cargo test --features encryption --verbose
