name: Swift

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v1
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        run: |
          cd ios/MMKV
          swift build
      - name: Run tests
        run: |
          cd ios/MMKV
          swift test