name: Swift Test

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'ios/**'
      - 'Package.swift'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'ios/**'
      - 'Package.swift'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v2
      - uses: actions/checkout@v4
      - name: Build
        run: |
          ./build_apple.sh
          cd ios/MMKV
          swift build
      - name: Run tests
        run: |
          cd ios/MMKV
          swift test