name: Swift Test

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'ios/**'
      - 'src/**'
      - 'Cargo.toml'
      - 'build.rs'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'ios/**'
      - 'src/**'
      - 'Cargo.toml'
      - 'build.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: swift-actions/setup-swift@v3
      - uses: actions/checkout@v6
      - name: Build
        run: |
          ./build_apple.sh
          perl -0777 -i -pe 's/\.binaryTarget\(name: "RustMMKV".*?\)/.binaryTarget(name: "RustMMKV", path: "ios\/MMKV\/RustMMKV.xcframework.zip")/gs' Package.swift
          cd ios/MMKV && swift build
      - name: Run tests
        run: |
          cd ios/MMKV
          swift test
